server:
  http2:
    enabled: true
  port: 8083
  tomcat:
    relaxed-query-chars: '|,{,},[,]'
    max-swallow-size: 30MB

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      #      ddl-auto: update
      #ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      properties:
        hibernate:
          format_sql: true
          use_sql_comments: true
    application:
      name: it-request-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/itRequest
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:root}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  jwt:
    secret: ${JWT_SECRET} # กุญแจลับสำหรับสร้างและตรวจสอบ JWT
    expiration: ${JWT_EXPIRATION} # อายุของ Token ในหน่วยมิลลิวินาที (1 วัน = 86400000 มิลลิวินาที)
    refresh:
      expiration: ${JWT_REFRESH_EXPIRATION}
  servlet:
    multipart:
        enabled: true
        max-file-size: 30MB
        max-request-size: 30MB
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs










